### ISSUE TITLE
Different Interfaces on Same Page

### ISSUE THREAD

**Issue by Mytonn** [tylerrichey/darkstatscore#8]
Hi. I have a two interfaces on my network; eth0 and eth1. 

My first rule is "dst 111.11.11.11 and dst port 1234" for **eth0**
My second rule is "not src net 192.168.1 and dst net 192.168.1" for **eth1** with OPTIONS="--local-only"

Could I merge those rules as one?

**Comment by tylerrichey** [comment]
I'm not sure. Those are just 'tcpdump filters', but you can't specify an interface as part of the filter (I don't think). If something like this doesn't work for you:
(dst 111.11.11.11 and dst port 1234) or (not src net 192.168.1 and dst net 192.168.1)

You can filter by mac address, ip, host port, etc, so maybe you can build a filter using those instead of interfaces?
